projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
        live: https://mirage-advanced-ykycbvfian.now.sh
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml